
[project]
name = "jonnor-toothbrush"
version = "0.0.1"
dependencies = [
    "mpflash",
    "esptool",
    "mpremote",
]

[project.optional-dependencies]
dev = [
    "pandas",
]

[tool.setuptools]
packages = ["software"]

