
name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install OS dependencies
      run: sudo add-apt-repository universe
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install MicroPython
      uses: BrianPugh/install-micropython@v2
      with:
        reference: v1.24.1
    - name: Install firmware dependencies
      run: bash -xe install_unix.sh
    - name: Install Python dependencies
      run: pip install .
    - name: Run firmware tests
      run: micropython firmware/test_toothbrush.py

  model:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install OS dependencies
      run: sudo add-apt-repository universe
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: pip install .[dev]

    - name: Install Python dependencies
      run: pip install emlearn-micropython/examples/har_trees
    - name: Run model train/evaluation
      env:
        PYTHONPATH: emlearn-micropython/examples/har_trees
      run: python -m software.model.evaluate --dataset combined --data-dir data/jonnor-brushing-1 --config data/jonnor-brushing-1/config.yaml
